import { Metadata } from "next";
import DetailPageLandingMain from "../../../components/templates/pageSections/DetailPageLandingMain"


export const metadata: Metadata = {
    title: "Shoe Detail",
    description: "Generated by create shoes store",
  };

export default async function Page({
    params,
}: {
    params: Promise<{ slug: string }>
}) {
    const slug = (await params).slug;
    return (
        <>
            <DetailPageLandingMain slug={slug} />
        </>
    )
}