import AddToCard from '@/components/templates/pageSections/AddToCard'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Your Cart",
    description: "Generated by create shoes store",
};

const page = () => {
    return (
        <>
            <AddToCard />
        </>
    )
}

export default page