import type { Metadata } from "next";
import "./globals.css";
import { NavbarDemo } from "@/components/templates/shared/Navbar";
import Footer from "@/components/templates/shared/Footer";


export const metadata: Metadata = {
  title: "Shoes Store by - Usman Dev",
  description: "Generated by usman dev shoes store",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <NavbarDemo />
        {children}
        <Footer />
      </body>
    </html>
  );
}
