import React from "react";
import LandingMain from "@/components/templates/pageSections/LandingMain";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shoes Store",
  description: "Generated by create shoes store",
};

export default function Home() {
  return (
    <>
      <LandingMain />
    </>
  );
}